logging status

diff --git a/picnic b/picnic
--- a/picnic
+++ b/picnic
@@ -18,7 +18,7 @@ function success {
 function check_os {
   case ${OSTYPE} in
     linux*)
-      success "OK"
+      success "The system is $(OSTYPE), ready to deploy"
       ;;
     *)
       error "$OSTYPE is NOT supported, exitting"
@@ -36,30 +36,44 @@ function package_download {
   cd ~/picnic-tmp
   wget "http://zlib.net/zlib-1.2.8.tar.gz"
   wget "https://www.kernel.org/pub/software/scm/git/git-2.8.1.tar.gz"
-  wget -O expat-2.1.1.tar.bz2 "http://downloads.sourceforge.net/project/expat/expat/2.1.1/expat-2.1.1.tar.bz2?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fexpat%2F&ts=1460701353&use_mirror=ufpr"
+  wget -O expat-2.1.0.tar.bz2 "http://osdn.jp/frs/g_redir.php?m=kent&f=%2Fexpat%2Fexpat%2F2.1.0%2Fexpat-2.1.0.tar.gz"
   wget "https://www.openssl.org/source/openssl-1.0.2g.tar.gz"
   wget "http://www.execve.net/curl/curl-7.48.0.tar.gz"
 }
 
 function install_zlib {
   cd ~/picnic-tmp
-  tar zxvf zlib-1.2.8.tar.gz
-  cd zlib-1.2.8
-  ./configure --prefix=$HOME/picnic-tools
-  make &&
-  make install &&
-  success "installed zlib to $HOME/picnic-tools"
+  tar zxf zlib-1.2.8.tar.gz  &&
+  cd zlib-1.2.8 &&
+  ./configure --prefix=$HOME/picnic-tools >> ~/picnic-tmp/install.log &&
+  make >> ~/picnic-tmp/install.log &&
+  make install >> ~/picnic-tmp/install.log
+  case "$?" in
+    0)
+    success "installed zlib to $HOME/picnic-tools"
+    ;;
+    1)
+    error "failed install zlib, see ~/picnic-tmp/install.log to more info"
+    ;;
+  esac
 }
 
 
 function install_git {
   cd ~/picnic-tmp
-  tar zxvf git-2.8.1.tar.gz
-  cd git-2.8.1
-  ./configure --prefix=$HOME/picnic-tools --with-curl=$HOME/picnic-tools/ --with-expat=$HOME/picnic-tools
-  make &&
-  make install &&
-  success "installed git to $HOME/picnic-tools"
+  tar zxf git-2.8.1.tar.gz &&
+  cd git-2.8.1 &&
+  ./configure --prefix=$HOME/picnic-tools --with-curl=$HOME/picnic-tools/ --with-expat=$HOME/picnic-tools  >> ~/picnic-tmp/install.log &&
+  make  >> ~/picnic-tmp/install.log &&
+  make install  >> ~/picnic-tmp/install.log
+  case "$?" in
+    0)
+    success "installed git to $HOME/picnic-tools"
+    ;;
+    1)
+    error "failed install git, see ~/picnic-tmp/install.log to more info"
+    ;;
+  esac
 }
 
 function install_curl {
@@ -71,33 +85,54 @@ function install_curl {
   # mv ~/picnic-tools/lib/x86_64-linux-gnu/* ~/picnic-tools/lib
   # rm -rf x86_64-linux-gnu/
 
-  tar zxvf curl-7.48.0.tar.gz
-  cd curl-7.48.0
-  ./buildconf
-  ./configure --with-ssl=$HOME/picnic-tools --prefix=$HOME/picnic-tools
-  make &&
-  make install &&
-  success "installed curl to $HOME/picnic-tools"
+  tar zxf curl-7.48.0.tar.gz &&
+  cd curl-7.48.0 &&
+  ./buildconf >> ~/picnic-tmp/install.log &&
+  ./configure --with-ssl=$HOME/picnic-tools --prefix=$HOME/picnic-tools >> ~/picnic-tmp/install.log &&
+  make >> ~/picnic-tmp/install.log &&
+  make install >> ~/picnic-tmp/install.log
+  case "$?" in
+    0)
+    success "installed curl to $HOME/picnic-tools"
+    ;;
+    1)
+    error "failed install curl, see ~/picnic-tmp/install.log to more info"
+    ;;
+  esac
 }
 
 function install_ssl {
   cd ~/picnic-tmp
-  tar zxvf openssl-1.0.2g.tar.gz
-  cd openssl-1.0.2g
-  ./config --prefix=$HOME/picnic-tools shared zlib-dynamic
-  make &&
-  make install &&
-  success "installed openssl to $HOME/picnic-tools"
+  tar zxf openssl-1.0.2g.tar.gz &&
+  cd openssl-1.0.2g &&
+  ./config --prefix=$HOME/picnic-tools shared zlib-dynamic >> ~/picnic-tmp/install.log &&
+  make >> ~/picnic-tmp/install.log &&
+  make install >> ~/picnic-tmp/install.log
+  case "$?" in
+    0)
+    success "installed openssl to $HOME/picnic-tools"
+    ;;
+    1)
+    error "failed install openssl, see ~/picnic-tmp/install.log to more info"
+    ;;
+  esac
 }
 
 function install_expat {
   cd ~/picnic-tmp
-  tar zxvf expat-2.1.0.tar.gz
-  cd expat-2.1.0
-  ./configure --prefix=$HOME/picnic-tools --disable-static
-  make &&
-  make install &&
-  success "installed expat to $HOME/picnic-tools"
+  tar zxf expat-2.1.0.tar.gz &&
+  cd expat-2.1.0 &&
+  ./configure --prefix=$HOME/picnic-tools --disable-static >> ~/picnic-tmp/install.log &&
+  make >> ~/picnic-tmp/install.log &&
+  make install >> ~/picnic-tmp/install.log
+  case "$?" in
+    0)
+    success "installed expat to $HOME/picnic-tools"
+    ;;
+    1)
+    error "failed install expat, see ~/picnic-tmp/install.log to more info"
+    ;;
+  esac
 }
 
 # SUBCOMMANDS
@@ -115,6 +150,7 @@ function picnic-unpack {
   mkdir ~/picnic-tools
   package_download
   export CPPFLAGS="-I$HOME/picnic-tools/include" LDFLAGS="-L$HOME/picnic-tools/lib"
+  echo "picnic unpack $(date)" > ~/picnic-tmp/install.log
   install_zlib
   install_ssl
   install_curl
@@ -134,6 +170,7 @@ function picnic-reunpack {
   fi
   mkdir ~/picnic-tools
   export CPPFLAGS="-I$HOME/picnic-tools/include" LDFLAGS="-L$HOME/picnic-tools/lib"
+  echo "picnic reunpack $(date)" > ~/picnic-tmp/install.log
   install_zlib
   install_ssl
   install_curl
